### ISSUE TITLE
Missing options.py

### ISSUE THREAD

**Issue by uSpike** [smurfix/asynctelnet#6] opened 2021-04-20 14:20 UTC
Probably wasn't checked-in.

```
$ pytest tests/
ImportError while loading conftest '/home/jordan/src/asynctelnet/tests/conftest.py'.
tests/conftest.py:5: in <module>
    from tests.accessories import shell as shell_, Server
tests/accessories.py:6: in <module>
    from asynctelnet.server import server_loop,TelnetServer
asynctelnet/__init__.py:3: in <module>
    from .server_base import *      # noqa
asynctelnet/server_base.py:9: in <module>
    from .stream import TelnetStream
asynctelnet/stream.py:19: in <module>
    from .telopt import (Cmd, Opt,
asynctelnet/telopt.py:56: in <module>
    from .options import Opt
E   ModuleNotFoundError: No module named 'asynctelnet.options'
```

**Comment by smurfix** [comment] 2021-04-20 14:24
Check out the "split" branch (for now; I'll merge that back to main tomorrow or so).

**Comment by uSpike** [comment] 2021-04-20 14:58
Cool thanks, merged that.  Now I get:
```
ImportError while importing test module '/home/jordan/src/asynctelnet/tests/test_xdisploc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.8.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_xdisploc.py:7: in <module>
    from tests.accessories import (
E   ImportError: cannot import name 'unused_tcp_port' from 'tests.accessories' (/home/jordan/src/asynctelnet/tests/accessories.py)
```

**Comment by smurfix** [comment] 2021-04-20 15:20
The problem is that the library still needs a non-trivial amount of work: I need to factor out the options so that the library is generically useable instead of being hard-coded to some (few) standard options and usecases.

I hope to get the tests to pass by the weekend or so.

Closing this issue in favor of #1.

**Closed as completed by smurfix** 2021-04-20 15:20 UTC

**Comment by uSpike** [comment] 2021-05-11 19:06
https://github.com/smurfix/asynctelnet/blob/split/asynctelnet/stream.py#L28 still references `options.py` but it doesn't exist in the `split` branch.  Could this please be checked-in?

**Comment by uSpike** [comment] 2021-05-11 19:29
Sorry, there is the options subpackage.  I'm not sure what's going on, but my python can't see it when I pip install.  Will investigate.

**Comment by uSpike** [comment] 2021-05-11 19:33
OK, this is fixed in https://github.com/smurfix/asynctelnet/pull/7/commits/dd541a564c16dffd82e76a95d94eb9e0801a6c51
